# Generated by Django 5.0.3 on 2024-03-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/images')),
            ],
        ),
        migrations.CreateModel(
            name='homeplants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('desc', models.TextField()),
                ('startprice', models.IntegerField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='home/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='home/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='home/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.categoryplant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.categoryplant')),
            ],
        ),
    ]
