# Generated by Django 5.0.3 on 2024-03-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryplant',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
