# Generated by Django 5.0.3 on 2024-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_categoryplant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeplants',
            name='stock',
            field=models.IntegerField(default=2),
        ),
    ]
