# Generated by Django 5.0.3 on 2024-04-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_homeplants_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='fertilizer/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='fertilizer/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='fertilizer/images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.categoryplant')),
            ],
        ),
    ]
