# Generated by Django 5.0.3 on 2024-04-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_fertilizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
