# Generated by Django 5.0.3 on 2024-04-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_alter_fertilizer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryfertilizer',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='category/fertilizer')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='category/fertilizer')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='category/fertilizer')),
            ],
        ),
    ]
