# Generated by Django 5.0.3 on 2024-04-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_alter_fertilizer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.categoryfertilizer'),
        ),
    ]
