# Generated by Django 5.0.3 on 2024-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_alter_fertilizer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfertilizer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
