# Generated by Django 5.0.3 on 2024-05-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_product1'),
        ('plant', '0011_alter_categoryfertilizer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.categoryplant'),
        ),
        migrations.DeleteModel(
            name='categoryfertilizer',
        ),
    ]
