# Generated by Django 5.0.3 on 2024-05-07 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0013_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
