# Generated by Django 5.0.3 on 2024-05-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0014_product_offer_price_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=95),
        ),
    ]
