# Generated by Django 5.0.3 on 2024-03-23 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product1'),
        ('plant', '0004_homeplants_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.homeplants'),
        ),
    ]
