# Generated by Django 5.0.3 on 2024-03-28 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_product1'),
        ('plant', '0004_homeplants_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(max_length=35)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product1',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('item_count', models.BigIntegerField()),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='pending', max_length=35)),
                ('order_status', models.CharField(default='pending', max_length=35)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
