# Generated by Django 5.0.3 on 2024-04-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_account_remove_cart_product1_order'),
        ('plant', '0011_alter_categoryfertilizer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plant.categoryfertilizer'),
            preserve_default=False,
        ),
    ]
