# Generated by Django 5.0.3 on 2024-05-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_rename_orders1_orders'),
        ('plant', '0016_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('house', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(default='Moscow', max_length=255)),
                ('message_to_seller', models.TextField(blank=True, null=True)),
                ('item_count', models.BigIntegerField()),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='pending', max_length=35)),
                ('order_status', models.CharField(default='pending', max_length=35)),
                ('shipping_info', models.CharField(choices=[('express', 'Express delivery (3-4 days via Fedex)'), ('post_office', 'Post office (20-30 days via post)'), ('self_pickup', 'Self pick-up (Come to our shop)')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
