# Generated by Django 5.0.3 on 2024-05-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_orders1_delete_orders'),
        ('plant', '0016_alter_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders1',
            new_name='Orders',
        ),
    ]
