# Generated by Django 5.0.3 on 2024-05-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_rename_orders1_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shipping_info',
        ),
    ]
