# Generated by Django 5.0.3 on 2024-05-09 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_orders_shipping_info'),
        ('plant', '0016_alter_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('house', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(default='Moscow', max_length=255)),
                ('message_to_seller', models.TextField(blank=True, null=True)),
                ('item_count', models.BigIntegerField()),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='pending', max_length=35)),
                ('order_status', models.CharField(default='pending', max_length=35)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
