# Generated by Django 5.0.3 on 2024-05-09 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_orders1_delete_orders'),
        ('plant', '0016_alter_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders1',
            new_name='Orders',
        ),
    ]
