# Generated by Django 5.0.3 on 2024-06-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_rename_orders1_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(default='India', max_length=255),
        ),
    ]
