# Generated by Django 5.0.3 on 2024-06-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_orders_order_id_orders_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
