# Generated by Django 5.0.3 on 2024-06-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_count',
            field=models.BigIntegerField(blank=True),
        ),
    ]
