# Generated by Django 5.0.3 on 2024-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_orders_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_count',
            field=models.BigIntegerField(default=1),
        ),
    ]
