# Generated by Django 5.0.3 on 2024-06-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_orders_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total',
        ),
        migrations.AlterField(
            model_name='orders',
            name='item_count',
            field=models.BigIntegerField(),
        ),
    ]
