# Generated by Django 5.0.3 on 2024-06-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_remove_orders_total_alter_orders_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_payment_id',
        ),
    ]
