# Generated by Django 5.0.3 on 2024-06-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
