# Generated by Django 5.0.3 on 2024-06-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
