# Generated by Django 5.0.3 on 2024-06-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='razorpay_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
