# Generated by Django 5.0.3 on 2024-06-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_rename_razorpay_payment_id_payment_razorpay_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
